version: '3'

services:
  db:
    container_name: mysql
    image: mysql:ordery
    build:
      context: ./database
    ports:
      - 3306:3306
    networks:
      - ordery
    env_file:
      - .env
    restart: always

  api:
    container_name: api
    image: api:ordery
    build:
      context: ./api
    ports:
      - 3000:3000
    networks:
      - ordery
    volumes:
      - ./api:/home/node/app
    env_file:
      - .env
    depends_on:
      - db
    restart: always

networks:
  ordery:
    name: ordery
    driver: bridge
