CREATE DATABASE IF NOT EXISTS ordery;

CREATE TABEL IF NO EXISTS order (
	id INT AUTO_INCREMENT PRIMARY KEY,
	createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	price DECIMAL(10, 2)
	status VARCHAR(10)
);

