CREATE DATABASE IF NOT EXISTS ordery;
USE ordery;
CREATE TABLE IF NOT EXISTS `order` (
	id INT AUTO_INCREMENT PRIMARY KEY,
	createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	price DECIMAL(10, 2),
	status VARCHAR(10)
);
CREATE TABLE IF NOT EXISTS `product` (
	id INT AUTO_INCREMENT PRIMARY KEY,
	createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	name VARCHAR(20),
	image VARCHAR(70),
	qte DECIMAL(10, 2),
	price DECIMAL(10, 2),
	category VARCHAR(20)
);
